version: '3.4'

x-zoo-healthcheck: &zoo-healthcheck
  test: ["CMD", "echo", "srvr", "|", "nc", "-w", "1", "127.0.0.1","2181","|", "grep", "-qi", "zookeeper"]
  interval: 5s
  timeout: 1s
  retries: 5

x-kafka-healthcheck: &kafka-healthcheck
  test: ["CMD", "kafka-topics", "--list", "--zookeeper", "xxx"]
  interval: 5s
  timeout: 10s
  retries: 6


services:

  zoo010:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_INIT_LIMIT: 30
      ZOO_SYNC_LIMIT: 30
    healthcheck:
      <<: *zoo-healthcheck

  kafka010:
    image: confluentinc/cp-kafka:3.2.2
    restart: always
    depends_on:
      - zoo010
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka010:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo010:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      <<: *kafka-healthcheck
      test: ["CMD", "kafka-topics", "--list", "--zookeeper", "zoo010:2181"]


  zoo210:
    image: confluentinc/cp-kafka:5.1.2
    restart: always
    volumes:
      - "./kafka-playground/zk_server_jaas.conf:/conf/zk_server_jaas.conf"
    command:
      - /usr/bin/zookeeper-server-start
      - /etc/kafka/zookeeper.properties
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      KAFKA_OPTS: -Djava.security.auth.login.config=/conf/zk_server_jaas.conf
    healthcheck:
      <<: *zoo-healthcheck

  kafka210:
    image: confluentinc/cp-kafka:5.1.2
    restart: always
    volumes:
      - "./kafka-playground/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf"
    depends_on:
      - zoo210
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo210:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    healthcheck:
      <<: *kafka-healthcheck
      test: ["CMD", "kafka-topics", "--list", "--zookeeper", "zoo210:2181"]



